kind: pipeline
type: docker
name: default
trigger:
  branch: master

steps:
  - name: golangci-lint
    image: golangci/golangci-lint:latest
    depends_on:
      - clone
    environment:
      GOOS: js
      GOARCH: wasm
    commands:
      # generate missed static package
      - go get github.com/rakyll/statik
      - statik -src=./include/ -dest=./wasm/
      # run the linter
      - golangci-lint run ./wasm/
      - golangci-lint run ./server/

  - name: flake8
    image: pipelinecomponents/flake8:latest
    depends_on:
      - clone
    commands:
      - flake8
